{% set name = "curve-apps" %}
{% set version = "0.2.0a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed
  # curl -sL https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz | openssl sha256
  path: ../{{ name }}


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10.0,<3.11
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=3.10.0,<3.11
    - numpy >=1.26.0,<1.27.0
    - pydantic >=2.5.2,<2.6.0
    - scikit-image >=0.20.0,<0.21.0
    - scipy >=1.14.0,<1.15.0
    - tqdm >=4.66.1,<4.67.0
    - geoh5py >=0.10.0a1, <0.11
    - geoapps-utils >=0.4.0a1,<0.5
    - h5py >=3.2.1,<4.0.0
    - pillow >=10.3.0,<10.4.0

test:
  imports:
    - curve_apps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Find edges on 2D grids or vertices.'
  description: |
    Auto-detection of trends and edges in geoscientific data.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://mirageoscience-curve-apps.readthedocs-hosted.com/
  dev_url: https://github.com/MiraGeoscience/curve-apps

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
